version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build-and-deploy:
        docker:
            - image: circleci/node:16.8.0
        steps:
            - checkout
            - restore_cache:
                keys:
                - v1-deps-{{ checksum "package.json" }}
            - run: sudo npm i -g serverless npm@latest
            - run: sudo npm i -g jest
            - run: npm install
            - run: chmod +x ./.circleci/install-credentials.sh
            - run: ./.circleci/install-credentials.sh
            - save_cache:
                key: v1-deps-{{ checksum "package.json" }}
                paths:
                - node_modules            
            - run: sls deploy
workflows:
    build-and-deploy:
        jobs:
            - build-and-deploy:
                  context: serverlessProject
                  filters:
                      branches:
                          only:
                              - main
