version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build-and-deploy:
        docker:
            - image: circleci/node:16.8.0
        steps:
            - checkout
            - run:
                  command: sudo npm i -g serverless npm@latest
            - run:
                  command: sudo npm i -g jest
            - run:
                  command: npm install
            - run:
                  command: chmod +x ./.circleci/install-credentials.sh
            - run:
                  command: ./.circleci/install-credentials.sh
            - run:
                  command: sls deploy
workflows:
    build-and-deploy:
        jobs:
            - build-and-deploy:
                  context: serverlessProject
                  filters:
                      branches:
                          only:
                              - main
